// <auto-generated />
using System;
using AnimeFun.Service.DataFactory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeFun.Service.DataFactory.Migrations
{
    [DbContext(typeof(AnimeFunContext))]
    [Migration("20221027065800_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnimeFun.Core.Models.AnimeFun.Episode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoInfoId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VideoInfoId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("AnimeFun.Core.Models.AnimeFun.RecommendVideo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("EpisodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoInfoId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecommendVideos");
                });

            modelBuilder.Entity("AnimeFun.Core.Models.AnimeFun.VideoInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VideoInfos");
                });

            modelBuilder.Entity("AnimeFun.Core.Models.AnimeFun.VideoTag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VideoTags");
                });

            modelBuilder.Entity("VideoInfoVideoTag", b =>
                {
                    b.Property<string>("VideoInfosId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VideoTagsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VideoInfosId", "VideoTagsId");

                    b.HasIndex("VideoTagsId");

                    b.ToTable("VideoInfoVideoTag");
                });

            modelBuilder.Entity("AnimeFun.Core.Models.AnimeFun.Episode", b =>
                {
                    b.HasOne("AnimeFun.Core.Models.AnimeFun.VideoInfo", "VideoInfo")
                        .WithMany("Episodes")
                        .HasForeignKey("VideoInfoId");

                    b.Navigation("VideoInfo");
                });

            modelBuilder.Entity("VideoInfoVideoTag", b =>
                {
                    b.HasOne("AnimeFun.Core.Models.AnimeFun.VideoInfo", null)
                        .WithMany()
                        .HasForeignKey("VideoInfosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeFun.Core.Models.AnimeFun.VideoTag", null)
                        .WithMany()
                        .HasForeignKey("VideoTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeFun.Core.Models.AnimeFun.VideoInfo", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
